Additional design notes based on POC results
Ed-Fi-Alliance-OSS/Project-Tanager pull request #16
Opened 2024-05-03 21:45 UTC by stephenfuqua

2024-05-03 21:46 UTC, stephenfuqua commented on docs/DMS/PRIMARY-DATA-STORAGE/ALTERNATIVES-DESIGNS.md
> -# DMS Feature: Primary Data Storage
Moved design options to separate document.

2024-05-03 21:46 UTC, stephenfuqua commented on docs/DMS/PRIMARY-DATA-STORAGE/README.md
> +## Problems to solve via DB design
There are no changes in this requirements section.

2024-05-03 21:46 UTC, stephenfuqua commented on docs/DMS/PRIMARY-DATA-STORAGE/README.md
> +## Solution
Everything below is new.

2024-05-06 14:21 UTC, bradbanister requested changes
The DMS-125 branch is behind on the primary data storage documentation. I've since archived the original doc as docs/DMS/PRIMARY-DATA-STORAGE-alternatives.md. docs/DMS/PRIMARY-DATA-STORAGE.md was rewritten as Option B similar to here but with much more detailed information, and also a change to one foreign key relationship.

2024-05-06 16:22 UTC, bradbanister commented on docs/DMS/PRIMARY-DATA-STORAGE/README.md
> +  partition key without having to recompile the C# application.
I was thinking the number-of-partitions would be an app settings type thing, so no need to recompile. If the UUID -> partition key is fully encapsulated in a stored proc, wouldn't that mean the number-of-partition settings would have to be in some config table that gets queried a lot by the stored proc? If it's an app setting, either the C# could derive the partition key and pass it directly as a stored proc parameter, or the number-of-partitions config setting could be a parameter.

2024-05-06 16:33 UTC, bradbanister commented on docs/DMS/PRIMARY-DATA-STORAGE/README.md
> +  partition key without having to recompile the C# application.
I think we may also want the partition key computation to be in C# for the query table support. We wouldn't be able to do a simple insert into a query table without knowing the partition key of the document. If it were done in a stored proc, we'd have to get the partition key returned from the DB first. Doable but more complex than just having it to begin with.

2024-05-06 17:07 UTC, stephenfuqua commented
Closing to create a new PR with rebase.

2024-05-06 17:07 UTC, closed without merging

2024-05-06 17:08 UTC, stephenfuqua commented on docs/DMS/PRIMARY-DATA-STORAGE/README.md
> +  partition key without having to recompile the C# application.
Thinking about this...